config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/rate', to: 'static_pages#rate'
  namespace :users do
    resources :profiles, only: [:index, :show, :edit, :update]
  end
  resources :recruits, except: :index do
    get 'map', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :participations, only: [:create, :destroy]
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user, inverse_of: :participations
  belongs_to :recruit, inverse_of: :participations
  validates :user_id, presence: true
  validates :recruit_id, presence: true, uniqueness: { scope: :user_id }
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    @recruit = Recruit.find(params[:recruit_id])
    respond_to do |format|
      if current_user.permit_participate?(@recruit)
        current_user.participate(@recruit)
      else
        flash.now[:alert] = current_user.id == @recruit.user_id ? 'You are owner' : 'Please comment first'
      end
      format.js
    end
  end

  def destroy
    respond_to do |format|
      @recruit = current_user.participated_recruits.find(params[:recruit_id])
      current_user.unparticipate(@recruit)
      format.js
    end
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_participate.html.slim
= link_to 'I will Join', recruit_participations_path(recruit_id: @recruit.id), class: "join-btn", method: :post, remote: true 

app/views/participations/_participate_btn_area.html.slim
- if current_user.id == recruit.user_id
- elsif current_user.participated?(recruit)
  = render partial: 'participations/unparticipate'
- else
  = render partial: 'participations/participate'

app/views/participations/_participate_members.html.slim
- @recruit.participated_users.each do |participated_user|
  = link_to "•#{participated_user.user_name}", users_profile_path(participated_user), class: "member-name" 

app/views/participations/_participate_number.html.slim
i.fas.fa-user-friends.faa-wrench.animated-hover
= "(#{@recruit.participations.count})"

app/views/participations/_unparticipate.html.slim
= link_to 'changed my mind', recruit_participation_path(recruit_id: @recruit.id, id: current_user.participations.find_by(recruit_id: @recruit.id)), class: "delete_join-btn", method: :delete, remote: true 

app/views/participations/create.js.erb
var flash = document.querySelector(".flash")

<% if !(flash[:alert]) %>
  //Ajaxで変更部分
  document.querySelector(".recruit_show-inner-bottom-left").innerHTML = "<%= escape_javascript(render('participations/unparticipate')) %>"
  document.querySelector(".participate-names").innerHTML = "<%= escape_javascript(render('participations/participate_members')) %>"
  document.querySelector(".participate-number").innerHTML = "<%= escape_javascript(render('participate_number')) %>"
  // flash
  flash.classList.remove('flash__alert');
  flash.classList.add('flash__notice');
  flash.style.display = "block";
  flash.innerHTML = 'You joined this recruit!';
<% else %> 
  flash.classList.remove('flash__notice');
  flash.classList.add('flash__alert');
  flash.style.display = "block";
  flash.innerHTML = "<%= (flash[:alert]) %>"
<% end %>

flash.animate([{opacity: '0'}, {opacity: '1'}], 50)
setTimeout(function(){ 
  flash.style.display = "none"; 
}, 6000);

app/views/participations/destroy.js.erb
document.querySelector(".recruit_show-inner-bottom-left").innerHTML = "<%= escape_javascript(render('participations/participate')) %>"
document.querySelector(".participate-names").innerHTML = "<%= escape_javascript(render('participations/participate_members')) %>"
document.querySelector(".participate-number").innerHTML = "<%= escape_javascript(render('participate_number')) %>"