config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/rate', to: 'static_pages#rate'
  namespace :users do
    resources :profiles, only: [:index, :show, :edit, :update]
  end
  resources :recruits, except: :index do
    get 'map', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :participations, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recruit
  validates :user_id, presence: true
  validates :recruit_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @recruit = Recruit.find(params[:recruit_id])
    comment = @recruit.comments.build(comment_params)
    comment.user_id = current_user.id
    respond_to do |format|
      if comment.save
        format.js
      else
        format.html { render 'recruits/show' }
      end
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    respond_to do |format|
      @comment.destroy!
      format.js
    end
  end

  private

    def comment_params
      params.permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_bubble.html.slim
= simple_format(h(comment.content), {}, sanitize: false, wrapper_tag: "p") 
.comment_index_delete
  - if comment.content.present? && current_user == comment.user
    = link_to 'delete', recruit_comment_path(recruit_id: recruit, id: comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" }, remote: true

app/views/comments/_comment_index.html.slim
- recruit.comments.each do |comment|
  .comment_index-item class="comment-#{comment.id}"  
    - if comment.user != recruit.user
      .comment_index-item-left
        .comment_index-image
          = link_to users_profile_path(comment.user)
            = render partial: './users/profiles/image', locals: { user: comment.user }
        .comment_index-comment
          = render partial: 'comments/comment_bubble', locals: { recruit: recruit, comment: comment }
    - else comment.user == recruit.user
      .comment_index-item-right
        .comment_index-comment
            = render partial: 'comments/comment_bubble', locals: { recruit: recruit, comment: comment }
        .comment_index-image
          = link_to users_profile_path(comment.user)
            = render partial: './users/profiles/image', locals: { user: comment.user }

app/views/comments/_comment_number.html.slim
i.far.fa-comment-dots
= "(#{recruit.comments.count})"

app/views/comments/create.js.erb
document.querySelector(".comment_index").innerHTML = "<%= escape_javascript(render partial: 'comments/comment_index', locals: { recruit: @recruit } ) %>"
document.querySelector(".comment-number").innerHTML = "<%= escape_javascript(render partial: 'comments/comment_number', locals: { recruit: @recruit } ) %>"
document.querySelector(".comment-area").value = ""

app/views/comments/destroy.js.erb
document.querySelector(".comment-<%= @comment.id %>").remove();
document.querySelector(".comment-number").innerHTML = "<%= escape_javascript(render partial: 'comments/comment_number', locals: { recruit: Recruit.find(params[:recruit_id]) } ) %>"