config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/rate', to: 'static_pages#rate'
  namespace :users do
    resources :profiles, only: [:index, :show, :edit, :update]
  end
  resources :recruits, except: :index do
    get 'map', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :participations, only: [:create, :destroy]
  end
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  include Scope
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :participated_users, through: :participations, source: :user
  scope :happen_recent, -> { order(date_time: :desc) }
  scope :feature, -> { where('date_time >= ?', Time.zone.now.beginning_of_day) }
  scope :upcoming, -> { order(date_time: :asc).feature }
  validates :user_id, presence: true
  validates :date_time, presence: true
  validates :hour, presence: true, numericality: { less_than_or_equal_to: 24 }
  validates :country, presence: true
  validates :city, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }

  def feature? 
    date_time > Time.zone.now.beginning_of_day
  end
end

app/controllers/recruit_controller.rb
class RecruitController < ApplicationController
  def show
    @recruit = Recruit.find(params[:id])
  end

  def new
    @recruit = Recruit.new
  end

  def create
    @recruit = current_user.recruits.build(recruit_params)
    if @recruit.save
      flash[:notice] = 'Recruit created!'
      redirect_to root_path
    else
      render new_recruit_path
    end
  end

  def edit
    @recruit = Recruit.find(params[:id])
  end

  def update
    @recruit = Recruit.find(params[:id])
    if @recruit.update!(recruit_params)
      # flash[:notice] = 'Recruit updated!'
      redirect_to root_path, notice: 'Recruit updated!'
    else
      render edit_recruit_path
    end
  end

  def destroy
    recruit = Recruit.find(params[:id])
    recruit.destroy
    redirect_to root_path, notice: 'Recruit deleted!'
  end

  private

    def recruit_params
      params.require(:recruit).permit(:date_time, :hour, :country, :city, :title, :content)
    end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  include Map

  def show
    @recruit = Recruit.find(params[:id])
  end

  def new
    if profile_blank_check?
      flash[:alert] = 'Please fill out your profile'
      redirect_to edit_users_profile_path(current_user)
    else
      @recruit = Recruit.new
    end
  end

  def create
    @recruit = current_user.recruits.build(recruit_params)
    if profile_blank_check?
      flash[:alert] = 'Please fill out your profile'
      redirect_to edit_users_profile_path(current_user)
    elsif @recruit.save
      flash[:notice] = 'Recruit created!'
      redirect_to @recruit
    else
      render :new
    end
  end

  def edit
    @recruit = Recruit.find(params[:id])
  end

  def update
    @recruit = Recruit.find(params[:id])
    if @recruit.update(recruit_params)
      flash[:notice] = 'Recruit updated!'
      redirect_to @recruit
    else
      render :edit
    end
  end

  def destroy
    recruit = Recruit.find(params[:id])
    recruit.destroy!
    flash[:notice] = 'Recruit deleted!'
    redirect_to root_path
  end

  def map
    @feature_recruits_json = feature_recruits_json
  end

  private

    def recruit_params
      params.require(:recruit).permit(:date_time, :hour, :country, :city, :title, :content)
    end

    def profile_blank_check?
      [current_user.gender, current_user.origin, current_user.current_country,
       current_user.language_1, current_user.introduce].any?(&:blank?)
    end
end

app/helpers/recruit_helper.rb
module RecruitHelper
end

app/views/recruits/_blank.html.slim
.recruit-dummy
  = link_to new_recruit_path, class: "recruit_create"
    .recruit-blank
      h3.recruit-title Create New Recruit
      .recruit-info
        p Title?
        p When?
        p Where?
        p How long?
        p About your plan?
    .recruit_index-blank-1
    .recruit_index-blank-2
    .recruit_index-blank-3
    .recruit_index-blank-4

app/views/recruits/_form.html.slim
= form_with model: recruit, local: true do |f|
  .field.recruit_new_content
    = f.label :title, 'Title:'
    = f.text_field :title, placeholder: "Let's go grab some beer!"
  .field.recruit_new_datetime
    = f.label :date_time, 'When:'
    = f.datetime_select :date_time, minute_step: 15, order:[:day, :month, :year], start_year: Time.now.year + 2, end_year: Time.now.year
  .field.recruit_new_hour
    = f.label :hour, 'How long(h):'
    = f.select :hour, (0.5..24).step(0.5).to_a
  .recruit_new-where
    .field.recruit_new_place
      = f.label :address, 'Meeting City:'
      = f.text_field :address, value: city, placeholder: "Tokyo", id: :autocomplete_address
    .field.recruit_new_country
      / = f.label :country, 'Meeting Country:'
      = f.hidden_field :country, id: :country
    .field.recruit_new_city
      / = f.label :city, 'Meeting City:'
      = f.hidden_field :city, id: :locality
  .field.recruit_new_content
    = f.label :content, 'About your plan:'
    = f.text_area :content, placeholder: "I wanna try Japanese Sake at an Izakaya! Shall we?"
  .field.recruit_form-btn
    .actions
      = f.submit "Save", class: "btn"

= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{Rails.application.credentials.dig(:GOOGLE_API_SERVER_KEY)}"
= javascript_pack_tag 'autocomplete'

app/views/recruits/_index.html.slim
- recruits.each do |recruit|
  .recruit_index-dummy
    .recruit_index-item
      = link_to recruit
        h4.recruit_index-item-title
          = recruit.title
      .recruit_index-item-middle
        .user-image-name
          .image
            = link_to users_profile_path(recruit.user)
              = render partial: './users/profiles/image', locals: { user: recruit.user }
          .recruit-name
            span Host 
            span  = link_to recruit.user.user_name, users_profile_path(recruit.user)
        = link_to recruit
          .recruit_index-item-texts
            = render partial: './recruits/simpleRecruitInfo', locals: { recruit: recruit }
      .recruit_index-item-bottom
        span.comment-icon
          i.far.fa-comment-dots
          = "(#{recruit.comments.count})"
        span.join-icon
          i.fas.fa-user-friends.faa-wrench.animated-hover
          = "(#{recruit.participations.count})"

app/views/recruits/_search.html.slim
= search_form_for(@q, url: root_path, method: :get, class: '', remote: true) do |f|
  = f.country_select :country_cont, { class: 'form-control', include_blank: 'All Countries' }
  = button_tag type: 'submit', class: 'btn' do
    i.fas.fa-search


  / .form-group.row
  /   = f.label :country_cont, 'Where', class: 'col-sm-2 col-form-label'
  /   .col-m-10
  /     = f.search_field :country_cont, class: 'form-control', placeholder: "Country, State, City, National Parks, Trails"
  / .form-group.row
  /   = f.label :date_time_cont, 'When', class: 'col-sm-2 col-form-label'
  /   .col-m-10
  /     = f.search_field :date_time_gteq, class: 'form-control'
  / .form-group
  /   = button_tag type: 'submit', class: 'btn btn-primary' do
  /     i.fas.fa-search
    

app/views/recruits/_simpleRecruitInfo.html.slim
.recruit-items
  span.when.recruit-words When:
  .when-info.user-info
    span.date_time
      = recruit.date_time.strftime('%Y/%-m/%-d(%a)')
    span.date_time
      = recruit.date_time.strftime('%-H:%M')
.recruit-items
  span.where.recruit-words Where: 
  .user-info
    span = "#{recruit.city}_"
    span = country_name(recruit.country)
    span.country_flag = country_flag(recruit.country)

app/views/recruits/_unparticipate.html.slim
= link_to 'changed my mind', recruit_participation_path(recruit_id: @recruit.id, id: current_user.participations.find_by(recruit_id: @recruit.id)), class: "delete_join-btn", method: :delete, remote: true 


/ <%= button_to tweet_like_path(like, tweet_id: tweet.id), method: :delete, id: "like-button", remote: true do %>

app/views/recruits/edit.html.slim
.recruit_form-wrapper
  .recruit_form-container
    h2.recruit_form-title Edit Recruit
    .recruit_form-inner
      = render "devise/shared/error_messages", resource: @recruit
      = render partial: 'form', locals: { recruit: @recruit, 
                                          country: @recruit.country,
                                          city: @recruit.city }

app/views/recruits/map.html.slim
#map
#hoge data-resource = @feature_recruits_json
javascript:
  const recruits_data = JSON.parse(document.getElementById('hoge').dataset.resource);
  function initMap() {
    // 日本の中央を表示する
    const defaultSettings = {zoom: 2.4, center: {lat: 30, lng: 0}};
    const map = new google.maps.Map(
      document.querySelector('#map'),
      defaultSettings
    );

    // 現在表示されているinfoWindowオブジェクト
    let currentWindow;

    recruits_data.map(d => {
      var contentString = 
      '<div id="content">'+
        `<p><a href=/recruits/${d.id}>${d.title}</a><p>`+
        `<p>@${d.city}_${d.country}<p>`+
      //  `<img src=http://localhost:3000/${d.user.image} width="200px">`+
      '</div>';

      // 画像の調整
      var image = {
    //    url: 'http://hibana.xii.jp/icon/pin/004/c18.png',
        url: d.user.image,
        // This marker is 20 pixels wide by 32 pixels high.
        scaledSize: new google.maps.Size(50, 50),
    //    // The origin for this image is (0, 0).
    //    origin: new google.maps.Point(0, 0),
    //    // The anchor for this image is the base of the flagpole at (0, 32).
        anchor: new google.maps.Point(0, 32)
      };

      // マーカーをつける
      const marker = new google.maps.Marker({
        position: {lat: d.lat, lng: d.lng},
        animation: google.maps.Animation.DROP,
        map: map,
        icon: image,
      });

      // マーカークリックしたら地名をポップアップさせる
      marker.addListener('click', () => {
        currentWindow && currentWindow.close();
        const infoWindow = new google.maps.InfoWindow({content: contentString});
        infoWindow.open(map, marker);
        currentWindow = infoWindow;
      });
    });
  }

script async="" defer="defer" src="https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials.dig(:GOOGLE_API_SERVER_KEY)}&callback=initMap"  

app/views/recruits/new.html.slim
.recruit_form-wrapper
  .recruit_form-container
    h2.recruit_form-title Create Recruit
    .recruit_form-inner
      = render "devise/shared/error_messages", resource: @recruit
      = render partial: 'form', locals: { recruit: @recruit, 
                                          country: @recruit.country,
                                          city: @recruit.city }

app/views/recruits/show.html.slim
.flash
.recruit_show-wrapper
  .recruit_show-container
    .recruit_show-dummy
      .recruit_show-inner
        h2.recruit_show-inner-title
          = @recruit.title
        .recruit_show-inner-middle
          .recruit_show-inner-middle-left
            .recruit_show-inner-profileInfo
              .recruit_show-inner-image
                = link_to users_profile_path(@recruit.user)
                  = render partial: './users/profiles/image', locals: { user: @recruit.user }
              .recruit_show-inner-name
                span Host: 
                span.user_name = @recruit.user.user_name 
                / - if @recruit.user.age.present?
                /   span.age = "(#{@recruit.user.age})"
                / - if @recruit.user.gender.present?
                /   span.gender = @recruit.user.gender
                / = render partial: './users/profiles/simpleInfo', locals: { user: @recruit.user }
            .recruit_show-inner-participate
              p ☆Joined Member☆
              .participate-names
                = render partial: 'participations/participate_members'
          
          .recruit_show-inner-recruitInfo
            = render partial: './recruits/simpleRecruitInfo', locals: { recruit: @recruit }
            .recruit-items
              span.how_long.recruit-words How long:
              .user-info
                span = "#{@recruit.hour}h"

            .recruit-items
              p.my_plan.recruit-words My plan:
              p.user-info.recruit-content = @recruit.content
        .recruit_show-inner-bottom
          - if @recruit.feature?
            .recruit_show-inner-bottom-left
              = render partial: 'participations/participate_btn_area', locals: { recruit: @recruit }
          .recruit_show-inner-bottom-right
            - if current_user == @recruit.user
              = link_to edit_recruit_path(@recruit), method: :get do
                i.fas.fa-edit
              = link_to @recruit, method: :delete, data: { confirm: "Are you sure you want to delete #{@recruit.title}?" }
                i.far.fa-trash-alt
            span.comment-number
              = render partial: 'comments/comment_number', locals: { recruit: @recruit }
            span.participate-number
              = render partial: 'participations/participate_number', locals: { recruit: @recruit }

  .comment-container
    .comment-inner
      - if @recruit.feature?
        .comment_new
          .comment_new-inner
            = form_with url: recruit_comments_path(@recruit), remote: true do |f|
              .field.comment_new_content
                = f.text_area :content, placeholder: "Write your comment", class: "comment-area"
              .field.comment_new-btn
                = f.submit "Comment", class: "btn"

      .comment_index
        = render partial: 'comments/comment_index', locals: { recruit: @recruit }
          