config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/rate', to: 'static_pages#rate'
  namespace :users do
    resources :profiles, only: [:index, :show, :edit, :update]
  end
  resources :recruits, except: :index do
    get 'map', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :participations, only: [:create, :destroy]
  end
end

app/views/layouts/_flash.html.slim
- flash.each do |key, value|
  = content_tag(:div, value.html_safe, class: "flash flash__#{key}")

app/views/layouts/_header.html.slim
header.fixed-top
  .navbar
    .container
      = link_to root_path, class: "logo"
        = image_pack_tag 'logo.png'
        p Solopacker
      ul.nav.navbar-right
        li
          = link_to "Home", root_path, id: "home"
        - if user_signed_in?
          li
            = link_to "Map", map_recruits_path, id: "Map"
          li
            = link_to "Members", users_profiles_path, id: "member"
          li
            = link_to "Rate", rate_path, id: "rate"
          li.dropdown 
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              = render partial: 'users/profiles/image', locals: { user: current_user }
              / | Account
              b.caret
            ul.dropdown-menu
              li
                = link_to "Profile", users_profile_path(current_user), id: "profile"
              li
                = link_to "About", about_path, id: "about"
              li.divider
              li
                = link_to "Sign out", destroy_user_session_path, method: "delete", id: "sign_out"
        - else
          = link_to "Sign in", new_user_session_path, id: "sign_in"


          / edit_users_profile_path(current_user)




    

app/views/layouts/_pagination.html.slim
= paginate object, remote: true
  / = page_entries_info object

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Solopacker
    = csrf_meta_tags
    = csp_meta_tag
    = Gon::Base.render_data
    / = javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{Rails.application.credentials.dig(:GOOGLE_API_SERVER_KEY)}"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" media="all" rel="stylesheet" type="text/css" /
    link href="https://fonts.googleapis.com/css?family=Delius|Handlee|Mali|Sriracha|Sue+Ellen+Francisco&display=swap" rel="stylesheet"
    = favicon_link_tag('logo.png')
  body
    = render 'layouts/header'
    = render 'layouts/flash'
    = yield
    / = debug(params) if Rails.env.development?